export interface RouteMetadata {
  method: string
  path: string
  auth: string
  category: string
  description: string
}

export const ROUTES_METADATA: RouteMetadata[] = [
  { method: 'PAGE', path: '/', auth: 'public', category: 'frontend', description: 'Landing page' },
  { method: 'PAGE', path: '/login', auth: 'public', category: 'frontend', description: 'Login page (email/password + Google OAuth)' },
  { method: 'PAGE', path: '/dev', auth: 'superAdmin', category: 'frontend', description: 'Dev console (SUPER_ADMIN only)' },
  { method: 'PAGE', path: '/admin', auth: 'admin', category: 'frontend', description: 'Admin console (ADMIN+)' },
  { method: 'PAGE', path: '/pm', auth: 'authenticated', category: 'frontend', description: 'Project Manager (all authenticated)' },
  { method: 'PAGE', path: '/settings', auth: 'authenticated', category: 'frontend', description: 'User settings (all authenticated)' },
  { method: 'PAGE', path: '/dashboard', auth: 'admin', category: 'frontend', description: 'Legacy — redirects to /admin' },
  { method: 'PAGE', path: '/profile', auth: 'authenticated', category: 'frontend', description: 'Legacy — redirects to /settings' },
  { method: 'PAGE', path: '/blocked', auth: 'authenticated', category: 'frontend', description: 'Blocked user info page' },
  { method: 'POST', path: '/api/auth/login', auth: 'public', category: 'auth', description: 'Email/password login' },
  { method: 'POST', path: '/api/auth/logout', auth: 'authenticated', category: 'auth', description: 'Logout (delete session)' },
  { method: 'GET', path: '/api/auth/session', auth: 'public', category: 'auth', description: 'Check current session' },
  { method: 'GET/POST', path: '/api/auth/*', auth: 'public', category: 'auth', description: 'Better Auth handler (sign-in, sign-out, OAuth callback, session)' },
  { method: 'GET', path: '/api/admin/users', auth: 'superAdmin', category: 'admin', description: 'List all users' },
  { method: 'PUT', path: '/api/admin/users/:id/role', auth: 'superAdmin', category: 'admin', description: 'Change user role' },
  { method: 'PUT', path: '/api/admin/users/:id/block', auth: 'superAdmin', category: 'admin', description: 'Block/unblock user' },
  { method: 'GET', path: '/api/admin/presence', auth: 'superAdmin', category: 'admin', description: 'Online user IDs' },
  { method: 'GET', path: '/api/admin/logs/app', auth: 'superAdmin', category: 'admin', description: 'App logs (Redis)' },
  { method: 'GET', path: '/api/admin/logs/audit', auth: 'superAdmin', category: 'admin', description: 'Audit logs (DB)' },
  { method: 'DELETE', path: '/api/admin/logs/app', auth: 'superAdmin', category: 'admin', description: 'Clear app logs' },
  { method: 'DELETE', path: '/api/admin/logs/audit', auth: 'superAdmin', category: 'admin', description: 'Clear audit logs' },
  { method: 'GET', path: '/api/admin/schema', auth: 'superAdmin', category: 'admin', description: 'Database schema (Prisma)' },
  { method: 'GET', path: '/api/admin/routes', auth: 'superAdmin', category: 'admin', description: 'Routes metadata' },
  { method: 'GET', path: '/api/admin/project-structure', auth: 'superAdmin', category: 'admin', description: 'Project file structure' },
  { method: 'GET', path: '/api/admin/env-map', auth: 'superAdmin', category: 'admin', description: 'Environment variables map' },
  { method: 'GET', path: '/api/admin/test-coverage', auth: 'superAdmin', category: 'admin', description: 'Test coverage mapping' },
  { method: 'GET', path: '/api/admin/dependencies', auth: 'superAdmin', category: 'admin', description: 'NPM dependencies graph' },
  { method: 'GET', path: '/api/admin/migrations', auth: 'superAdmin', category: 'admin', description: 'Migration timeline' },
  { method: 'GET', path: '/api/admin/sessions', auth: 'superAdmin', category: 'admin', description: 'Active sessions (live)' },
  { method: 'POST', path: '/webhooks/aw', auth: 'bearer', category: 'pm-watch', description: 'ActivityWatch ingestion webhook (Bearer DB token or PMW_WEBHOOK_TOKEN fallback)' },
  { method: 'GET', path: '/api/me/agents', auth: 'authenticated', category: 'pm-watch', description: "Current user's own pm-watch agents" },
  { method: 'GET', path: '/api/me/agents/today', auth: 'authenticated', category: 'pm-watch', description: "Total window-bucket seconds tracked today" },
  { method: 'GET', path: '/api/me/preferences', auth: 'authenticated', category: 'user', description: 'Current user preferences' },
  { method: 'PUT', path: '/api/me/preferences', auth: 'authenticated', category: 'user', description: 'Update current user preferences' },
  { method: 'PUT', path: '/api/me/password', auth: 'authenticated', category: 'user', description: 'Change own password (requires currentPassword + newPassword, min 8 chars)' },
  { method: 'GET', path: '/api/me/sessions', auth: 'authenticated', category: 'user', description: 'List own active sessions with isCurrent flag' },
  { method: 'DELETE', path: '/api/me/sessions/others', auth: 'authenticated', category: 'user', description: 'Revoke all of own sessions except the current one' },
  { method: 'GET', path: '/api/me/audit', auth: 'authenticated', category: 'user', description: 'Recent 20 security-related audit events for current user' },
  { method: 'GET', path: '/api/me/notifications', auth: 'authenticated', category: 'notifications', description: 'List notifications (?limit=50&unread=1)' },
  { method: 'GET', path: '/api/me/notifications/unread-count', auth: 'authenticated', category: 'notifications', description: 'Unread notification count' },
  { method: 'POST', path: '/api/me/notifications/:id/read', auth: 'authenticated', category: 'notifications', description: 'Mark a notification as read' },
  { method: 'POST', path: '/api/me/notifications/read-all', auth: 'authenticated', category: 'notifications', description: 'Mark all notifications as read' },
  { method: 'DELETE', path: '/api/me/notifications/:id', auth: 'authenticated', category: 'notifications', description: 'Delete a notification' },
  { method: 'GET', path: '/api/me/team', auth: 'authenticated', category: 'team', description: "Teammates across user's projects with open/overdue task counts" },
  { method: 'GET', path: '/api/me/team-activity', auth: 'authenticated', category: 'team', description: "Recent task activity in user's shared projects" },
  { method: 'GET', path: '/api/admin/agents', auth: 'superAdmin', category: 'pm-watch', description: 'List pm-watch agents (with claim + event counts)' },
  { method: 'POST', path: '/api/admin/agents/:id/approve', auth: 'superAdmin', category: 'pm-watch', description: 'Approve agent and assign to user' },
  { method: 'POST', path: '/api/admin/agents/:id/revoke', auth: 'superAdmin', category: 'pm-watch', description: 'Revoke agent (blocks future ingestion)' },
  { method: 'GET', path: '/api/admin/webhook-tokens', auth: 'superAdmin', category: 'pm-watch', description: 'List webhook API tokens' },
  { method: 'POST', path: '/api/admin/webhook-tokens', auth: 'superAdmin', category: 'pm-watch', description: 'Create webhook token (returns plaintext once)' },
  { method: 'PATCH', path: '/api/admin/webhook-tokens/:id', auth: 'superAdmin', category: 'pm-watch', description: 'Disable / enable / revoke webhook token' },
  { method: 'DELETE', path: '/api/admin/webhook-tokens/:id', auth: 'superAdmin', category: 'pm-watch', description: 'Delete webhook token permanently' },
  { method: 'GET', path: '/api/admin/webhooks/stats', auth: 'superAdmin', category: 'pm-watch', description: 'Webhook monitor: 24h/7d aggregates + per-token/per-agent hits' },
  { method: 'GET', path: '/api/admin/webhooks/logs', auth: 'superAdmin', category: 'pm-watch', description: 'Webhook request log stream (filter: status=all|ok|fail|auth)' },
  { method: 'GET', path: '/api/users', auth: 'authenticated', category: 'users', description: 'Lightweight user directory for member/assignee pickers' },
  { method: 'GET', path: '/api/projects', auth: 'authenticated', category: 'projects', description: 'List projects user is a member of' },
  { method: 'POST', path: '/api/projects', auth: 'authenticated', category: 'projects', description: 'Create project (creator becomes OWNER)' },
  { method: 'GET', path: '/api/projects/:id', auth: 'authenticated', category: 'projects', description: 'Project detail with members + task count (members only)' },
  { method: 'PATCH', path: '/api/projects/:id', auth: 'authenticated', category: 'projects', description: 'Update project name/description/archived (OWNER or PM)' },
  { method: 'DELETE', path: '/api/projects/:id', auth: 'authenticated', category: 'projects', description: 'Delete project permanently (OWNER or SUPER_ADMIN)' },
  { method: 'POST', path: '/api/projects/:id/members', auth: 'authenticated', category: 'projects', description: 'Add member to project (OWNER, PM, or system admin)' },
  { method: 'PATCH', path: '/api/projects/:id/members/:userId', auth: 'authenticated', category: 'projects', description: 'Change member role' },
  { method: 'DELETE', path: '/api/projects/:id/members/:userId', auth: 'authenticated', category: 'projects', description: 'Remove member (OWNER, PM, or system admin)' },
  { method: 'POST', path: '/api/projects/:id/extend', auth: 'authenticated', category: 'projects', description: 'Extend project deadline (OWNER, PM, or system admin)' },
  { method: 'GET', path: '/api/projects/:id/extensions', auth: 'authenticated', category: 'projects', description: 'List deadline extension history (members only)' },
  { method: 'GET', path: '/api/milestones', auth: 'authenticated', category: 'projects', description: 'List milestones across all projects user is a member of' },
  { method: 'GET', path: '/api/projects/:id/milestones', auth: 'authenticated', category: 'projects', description: 'List project milestones (members only)' },
  { method: 'POST', path: '/api/projects/:id/milestones', auth: 'authenticated', category: 'projects', description: 'Create milestone (OWNER or PM)' },
  { method: 'PATCH', path: '/api/milestones/:id', auth: 'authenticated', category: 'projects', description: 'Update milestone or toggle completion (OWNER or PM)' },
  { method: 'DELETE', path: '/api/milestones/:id', auth: 'authenticated', category: 'projects', description: 'Delete milestone (OWNER or PM)' },
  { method: 'GET', path: '/api/tasks', auth: 'authenticated', category: 'tasks', description: 'List tasks (filter: projectId, status, kind, assigneeId, mine=1)' },
  { method: 'POST', path: '/api/tasks', auth: 'authenticated', category: 'tasks', description: 'Create task in a project (member only)' },
  { method: 'GET', path: '/api/tasks/:id', auth: 'authenticated', category: 'tasks', description: 'Task detail with comments + evidence (member only)' },
  { method: 'PATCH', path: '/api/tasks/:id', auth: 'authenticated', category: 'tasks', description: 'Update task fields (member only; status transitions enforced)' },
  { method: 'DELETE', path: '/api/tasks/:id', auth: 'authenticated', category: 'tasks', description: 'Delete task (reporter, OWNER/PM, or SUPER_ADMIN)' },
  { method: 'POST', path: '/api/tasks/bulk-delete', auth: 'authenticated', category: 'tasks', description: 'Bulk delete tasks' },
  { method: 'POST', path: '/api/tasks/:id/comments', auth: 'authenticated', category: 'tasks', description: 'Comment on task (member only)' },
  { method: 'POST', path: '/api/tasks/:id/evidence', auth: 'authenticated', category: 'tasks', description: 'Attach evidence to task (member only)' },
  { method: 'POST', path: '/api/tasks/:id/evidence/upload', auth: 'authenticated', category: 'tasks', description: 'Upload evidence file (multipart; max UPLOAD_MAX_BYTES)' },
  { method: 'GET', path: '/api/evidence/:file', auth: 'authenticated', category: 'tasks', description: "Stream evidence file (member of owning task's project)" },
  { method: 'GET', path: '/api/projects/:id/github/summary', auth: 'authenticated', category: 'github', description: 'GitHub repo stats for project' },
  { method: 'GET', path: '/api/projects/:id/github/feed', auth: 'authenticated', category: 'github', description: 'Paginated GitHub events for project' },
  { method: 'POST', path: '/webhooks/github', auth: 'hmac', category: 'github', description: 'GitHub webhook ingestion (HMAC SHA-256 via GITHUB_WEBHOOK_SECRET)' },
  { method: 'POST', path: '/mcp', auth: 'shared-secret', category: 'mcp', description: 'MCP HTTP fallback (Bearer MCP_SECRET; scope by NODE_ENV)' },
  { method: 'GET', path: '/api/projects/:id/tags', auth: 'authenticated', category: 'tasks', description: 'List project tags (member only)' },
  { method: 'POST', path: '/api/projects/:id/tags', auth: 'authenticated', category: 'tasks', description: 'Create project tag (member with write access)' },
  { method: 'PATCH', path: '/api/tags/:id', auth: 'authenticated', category: 'tasks', description: 'Rename/recolor tag' },
  { method: 'DELETE', path: '/api/tags/:id', auth: 'authenticated', category: 'tasks', description: 'Delete tag' },
  { method: 'POST', path: '/api/tasks/:id/dependencies', auth: 'authenticated', category: 'tasks', description: 'Add blocked-by dependency (same-project only)' },
  { method: 'DELETE', path: '/api/tasks/:id/dependencies/:blockedById', auth: 'authenticated', category: 'tasks', description: 'Remove blocked-by dependency' },
  { method: 'POST', path: '/api/tasks/:id/checklist', auth: 'authenticated', category: 'tasks', description: 'Add checklist item' },
  { method: 'PATCH', path: '/api/checklist/:id', auth: 'authenticated', category: 'tasks', description: 'Toggle/rename checklist item' },
  { method: 'DELETE', path: '/api/checklist/:id', auth: 'authenticated', category: 'tasks', description: 'Delete checklist item' },
  { method: 'GET', path: '/api/activity', auth: 'authenticated', category: 'activity', description: 'List my ActivityWatch events' },
  { method: 'GET', path: '/api/activity/summary', auth: 'authenticated', category: 'activity', description: 'Aggregate stats for my AW events' },
  { method: 'GET', path: '/api/activity/agents', auth: 'authenticated', category: 'activity', description: 'List my approved pm-watch agents' },
  { method: 'GET', path: '/api/activity/calendar', auth: 'authenticated', category: 'activity', description: 'Per-day event counts for a month' },
  { method: 'GET', path: '/api/activity/heatmap', auth: 'authenticated', category: 'activity', description: 'Per-day activity aggregates for a full year' },
  { method: 'GET', path: '/health', auth: 'public', category: 'utility', description: 'Health check' },
  { method: 'GET', path: '/api/version', auth: 'public', category: 'utility', description: 'App name + version from package.json' },
  { method: 'GET', path: '/api/hello', auth: 'public', category: 'utility', description: 'Hello world (GET)' },
  { method: 'PUT', path: '/api/hello', auth: 'public', category: 'utility', description: 'Hello world (PUT)' },
  { method: 'GET', path: '/api/hello/:name', auth: 'public', category: 'utility', description: 'Hello with name param' },
  { method: 'WS', path: '/ws/presence', auth: 'authenticated', category: 'realtime', description: 'Real-time presence tracking' },
]
